# 05.03.24
theme = "dark_plus"

[editor]
true-color = true
line-number = "relative"
rulers = [80, 120]
bufferline = "always"
auto-save = true
auto-format = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = true
